// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyhzhlgoiveljgdsyugn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5aHpobGdvaXZlbGpnZHN5dWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzQ1NTksImV4cCI6MjA2Njk1MDU1OX0.tJKQKvBr3ww15FlxfGOZoEO5Srn0CCwTdOSh_2OR3WI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});